
package com.tech.blog.helper;

import java.util.Arrays;
import java.util.List;

public class Skills {

    // List of available technical skills
    public static final List<String> TECHNICAL_SKILLS = Arrays.asList(
        "Java",
        "Python",
        "C++",
        "JavaScript",
        "HTML",
        "CSS",
        "SQL",
        "Ruby",
        "PHP",
        "Swift",
        "Objective-C",
        "C#",
        "React",
        "Angular",
        "Vue.js",
        "Node.js",
        "Express.js",
        "Spring",
        "Hibernate",
        "MongoDB",
        "Firebase",
        "Docker",
        "Kubernetes",
        "AWS",
        "Azure",
        "Google Cloud",
        "Git",
        "GitHub",
        "Bitbucket",
        "Jenkins",
        "Maven",
        "Gradle",
        "JUnit",
        "Selenium",
        "JUnit",
        "RESTful APIs",
        "SOAP",
        "GraphQL",
        "Microservices",
        "Blockchain",
        "Machine Learning",
        "Artificial Intelligence",
        "Data Science",
        "Big Data",
        "IoT",
        "AR/VR",
        "Game Development"
        // Add more technical skills as needed
    );

    // List of available soft skills
    public static final List<String> SOFT_SKILLS = Arrays.asList(
        "Communication",
        "Teamwork",
        "Problem-solving",
        "Time management",
        "Leadership",
        "Adaptability",
        "Creativity",
        "Critical thinking",
        "Decision making",
        "Flexibility",
        "Interpersonal skills",
        "Emotional intelligence",
        "Conflict resolution",
        "Stress management",
        "Negotiation",
        "Empathy",
        "Active listening",
        "Presentation skills",
        "Public speaking",
        "Networking",
        "Collaboration",
        "Initiative",
        "Attention to detail",
        "Organizational skills",
        "Multitasking",
        "Prioritization",
        "Self-motivation",
        "Resilience",
        "Positive attitude",
        "Team building",
        "Customer service",
        "Strategic planning",
        "Project management",
        "Time management",
        "Decision making",
        "Problem-solving",
        "Conflict resolution",
        "Leadership",
        "Emotional intelligence",
        "Adaptability",
        "Creativity",
        "Communication",
        "Listening skills",
        "Attention to detail",
        "Interpersonal skills",
        "Networking"
        // Add more soft skills as needed
    );
    
    public static final List<String> OCCUPATIONS = Arrays.asList(
    "Software Engineer",
    "Data Scientist",
    "Doctor",
    "Nurse",
    "Teacher",
    "Accountant",
    "Lawyer",
    "Marketing Manager",
    "Graphic Designer",
    "Web Developer",
    "Project Manager",
    "Financial Analyst",
    "HR Manager",
    "Product Manager",
    "Mechanical Engineer",
    "Civil Engineer",
    "Electrical Engineer",
    "Architect",
    "Chef",
    "Writer",
    "Journalist",
    "Photographer",
    "Artist",
    "Musician",
    "Actor/Actress",
    "Entrepreneur",
    "Sales Representative",
    "Consultant",
    "Police Officer",
    "Firefighter",
    "Paramedic",
    "Pilot",
    "Flight Attendant",
    "Military Officer",
    "Social Worker",
    "Therapist",
    "Veterinarian",
    "Dentist",
    "Pharmacist",
    "Biologist",
    "Chemist",
    "Physicist",
    "Geologist",
    "Psychologist",
    "Sociologist",
    "Anthropologist",
    "Historian",
    "Economist",
    "Political Scientist",
    "Philosopher",
    "Linguist",
    "Translator",
    "Librarian",
    "Curator",
    "Event Planner",
    "Fashion Designer",
    "Interior Designer",
    "Personal Trainer",
    "Coach",
    "Yoga Instructor",
    "Fitness Instructor",
    "Nutritionist",
    "Dietitian"
    // Add more occupations as needed
);

}
